"""
PathTracer.py - Custom Monte Carlo Path Tracer for Mitsuba 3 & Dr.Jit
Author: Dr. Changsik Lee (이창식 박사)

Features:
- Subclasses Mitsuba 3 ADIntegrator (the standard Python integrator base).
- Native Dr.Jit @dr.syntax with dr.hint(active, max_iterations=...) loop.
- Multiple Importance Sampling (MIS) with Power-2 balance heuristic.
- Next Event Estimation (NEE) with Direct Emitter Sampling.
- BSDF Importance Sampling with local-to-world ray propagation.
- Russian Roulette path termination with per-channel RGB max.
"""

import time
from pathlib import Path
from typing import Any, Optional, Tuple
import drjit as dr
import mitsuba as mi
from mitsuba.python.ad.integrators.common import ADIntegrator


def mis_weight(pdf_a, pdf_b):
    """
    Power-2 heuristic for Multiple Importance Sampling (MIS).
    w_a = (pdf_a^2) / (pdf_a^2 + pdf_b^2)
    """
    pdf_a2 = dr.sqr(pdf_a)
    pdf_b2 = dr.sqr(pdf_b)
    sum_pdf = pdf_a2 + pdf_b2
    return dr.select(sum_pdf != 0.0, pdf_a2 / sum_pdf, 0.0)


class CustomPathTracer(ADIntegrator):
    """
    Custom Monte Carlo Path Tracer inheriting from Mitsuba's ADIntegrator,
    providing full Pythonic wavefront rendering via @dr.syntax and Dr.Jit.
    """

    def __init__(self, props=mi.Properties()):
        super().__init__(props)
        self.use_nee = props.get("use_nee", True)

    @dr.syntax
    def sample(
        self,
        mode: dr.ADMode,
        scene: mi.Scene,
        sampler: mi.Sampler,
        ray: mi.Ray3f,
        depth: mi.UInt32 = mi.UInt32(0),
        δL: Optional[mi.Spectrum] = None,
        δaovs: Optional[mi.Spectrum] = None,
        state_in: Any = None,
        active: mi.Bool = True,
        **kwargs,
    ) -> Tuple[mi.Spectrum, mi.Bool, list, Any]:
        """
        Evaluate path tracing radiance for rays generated by sensor film/sampler.
        Conforms strictly to Mitsuba 3 ADIntegrator::sample interface.
        """
        del δL, δaovs, state_in, kwargs  # Unused in primal rendering mode

        # --------------------- Initialize loop state ---------------------
        ray = mi.Ray3f(ray)
        depth = mi.UInt32(0)
        L = mi.Color3f(0.0)
        β = mi.Color3f(1.0)
        η = mi.Float(1.0)
        active = mi.Bool(active)

        # Standard BSDF evaluation context
        bsdf_ctx = mi.BSDFContext()

        # Previous vertex cache for MIS
        si_prev = dr.zeros(mi.SurfaceInteraction3f)
        bsdf_pdf_prev = mi.Float(1.0)
        bsdf_delta_prev = mi.Bool(True)

        # Primary hit validity for alpha channel
        valid = mi.Bool(False)

        # --------------------- Main Wavefront Loop -----------------------
        while dr.hint(active, max_iterations=self.max_depth, label="CustomPathTracer"):
            # 1. Intersect ray with scene geometry
            si = scene.ray_intersect(ray, active=active)
            active &= si.is_valid()
            valid |= (depth == 0) & si.is_valid()

            # 2. Emission from intersected surface
            ds = mi.DirectionSample3f(scene, si=si, ref=si_prev)

            if dr.hint(not self.use_nee, mode="scalar"):
                # Pure Path Tracing: accumulate all emission directly
                L += β * ds.emitter.eval(si, active)
            else:
                # Next Event Estimation with MIS:
                # Direct hit on primary ray (depth == 0) or following a delta bounce has MIS weight 1.0.
                # Diffuse bounce uses Power-2 heuristic between BSDF sampling and Emitter sampling.
                mis = dr.select(
                    (depth == 0) | bsdf_delta_prev,
                    1.0,
                    mis_weight(
                        bsdf_pdf_prev,
                        scene.pdf_emitter_direction(si_prev, ds, ~bsdf_delta_prev),
                    ),
                )
                L += β * mis * ds.emitter.eval(si, active)

            # Check if rays can continue to the next bounce
            active_next = active & (depth + 1 < self.max_depth) & si.is_valid()
            bsdf = si.bsdf(ray)

            # 3. Next Event Estimation (Direct Emitter Direction Sampling)
            if dr.hint(self.use_nee, mode="scalar"):
                active_em = active_next & mi.has_flag(bsdf.flags(), mi.BSDFFlags.Smooth)

                ds_em, em_weight = scene.sample_emitter_direction(
                    si, sampler.next_2d(), True, active_em
                )
                active_em &= (ds_em.pdf != 0.0)

                wo = si.to_local(ds_em.d)
                bsdf_val_em, bsdf_pdf_em = bsdf.eval_pdf(bsdf_ctx, si, wo, active_em)
                mis_em = dr.select(ds_em.delta, 1.0, mis_weight(ds_em.pdf, bsdf_pdf_em))

                L += dr.select(active_em, β * mis_em * bsdf_val_em * em_weight, 0.0)

            # 4. Russian Roulette path termination
            β_max = dr.maximum(β.x, dr.maximum(β.y, β.z))
            active_next &= (β_max != 0.0)

            rr_prob = dr.minimum(β_max * dr.sqr(η), 0.95)
            rr_active = active_next & (depth >= self.rr_depth)

            β = dr.select(rr_active, β * dr.rcp(rr_prob), β)
            rr_continue = sampler.next_1d() < rr_prob
            active_next &= ~rr_active | rr_continue

            # 5. BSDF Importance Sampling for next indirect bounce
            bsdf_sample, bsdf_weight = bsdf.sample(
                bsdf_ctx, si, sampler.next_1d(), sampler.next_2d(), active_next
            )

            β *= bsdf_weight
            η *= bsdf_sample.eta
            ray = si.spawn_ray(si.to_world(bsdf_sample.wo))

            si_prev = dr.detach(si, True)
            bsdf_pdf_prev = bsdf_sample.pdf
            bsdf_delta_prev = mi.has_flag(bsdf_sample.sampled_type, mi.BSDFFlags.Delta)

            active = active_next & (bsdf_sample.pdf != 0.0)
            depth += 1

        return L, valid, [], None


# Register custom integrator with Mitsuba plugin manager
try:
    mi.register_integrator("custom_path", lambda props: CustomPathTracer(props))
except Exception:
    pass


def render_scene(
    scene_or_path,
    spp: int = 64,
    max_depth: int = 8,
    rr_depth: int = 5,
    use_nee: bool = True,
    output_path: str = "output_custom_path.png",
):
    """
    Convenience function to render a scene using CustomPathTracer.
    """
    if isinstance(scene_or_path, (str, Path)):
        print(f"[CustomPathTracer] Loading scene from: {scene_or_path}")
        scene = mi.load_file(str(scene_or_path))
    else:
        scene = scene_or_path

    # Instantiate custom integrator
    props = mi.Properties()
    props["max_depth"] = max_depth
    props["rr_depth"] = rr_depth
    props["use_nee"] = use_nee
    integrator = CustomPathTracer(props)

    print(
        f"[CustomPathTracer] Starting render with @dr.syntax (SPP={spp}, max_depth={max_depth}, NEE={use_nee})..."
    )
    start_time = time.time()

    # Render with custom integrator
    image = mi.render(scene, integrator=integrator, spp=spp)

    # Force JIT evaluation before measuring timing
    dr.eval(image)
    elapsed = time.time() - start_time
    print(f"[CustomPathTracer] Render completed in {elapsed:.2f} seconds.")

    # Save output image
    if output_path:
        out_p = Path(output_path)
        out_p.parent.mkdir(parents=True, exist_ok=True)
        mi.util.write_bitmap(str(out_p), image)
        print(f"[CustomPathTracer] Saved rendered image to: {out_p.resolve()}")

    return image
